#!/bin/bash
# $Id: myCmsRun,v 1.3 2007/05/24 11:29:30 loizides Exp $

if test -n "$CMSSW_VERSION"; then
    echo "$0: Running cmsRun for CMSSW version $CMSSW_VERSION"
else 
    echo "$0: CMSSW environment not properly set"
    exit 1
fi


DATESTR=`date +%s`
if test -z "$MYHISTOUTPUT"; then
    export MYHISTOUTPUT="myhistos-$DATESTR.root"
fi

if test -z "$MYOUTPUTFILE"; then
    export MYOUTPUTFILE="myoutput-$DATESTR.root"
fi


PRELOADLIB=$CMSSW_BASE/lib/$SCRAM_ARCH/libCLoizidesMyFixes.so
if test -e "$PRELOADLIB"; then
    export LD_PRELOAD=$PRELOADLIB
else
    PRELOADLIB=""
fi


if test -e "$1"; then 
    CFGTMP=/tmp/${USER}-mycmsrun-`basename ${1}`
    cp -a $1 $CFGTMP

    if test -n "`grep MYOUTPUTFILE $CFGTMP`"; then
        echo "$0: Using MYOUTPUTFILE: $MYOUTPUTFILE"
    fi

    if test -n "`grep MYHISTOUTPUT $CFGTMP`"; then
        echo "$0: Using MYHISTOUTPUT: $MYHISTOUTPUT"
    fi

    if test -n "$MYINPUTFILE"; then
        if test -n "`grep MYINPUTFILE $CFGTMP`"; then
            echo "$0: Using MYINPUTFILE: $MYINPUTFILE"
        fi

        if test -n "`grep MYMIXINPUTFILE $CFGTMP`"; then
            echo "$0: Using MYMIXINPUTFILE: $MYMIXINPUTFILE"
        fi

        cat $1 | sed "s#__MYINPUTFILE__#$MYINPUTFILE#" \
               | sed "s#__MYMIXINPUTFILE__#$MYMIXINPUTFILE#" \
               | sed "s#__MYOUTPUTFILE__#$MYOUTPUTFILE#" \
               | sed "s/__SEED1__/$RANDOM/"         | sed "s/__SEED2__/$RANDOM/"        \
               | sed "s/__SEED3__/$RANDOM/"         | sed "s/__SEED4__/$RANDOM/"        \
               | sed "s/__SEED5__/$RANDOM/"         | sed "s/__SEED6__/$RANDOM/"        \
               | sed "s/__SEED7__/$RANDOM/"         | sed "s/__SEED8__/$RANDOM/"        \
               | sed "s#__FILENAME__#$FILENAME#"    | sed "s#__EVENTS__#$EVENTS#"       \
               | sed "s/__FIRSTEVENTNUM__/$FEVNUM/" | sed "s/__FIRSTRUNNUM__/$FRUNNUM/" \
               | sed "s/__MAXEVENTS__/$MAXEVENTS/"  | sed "s/__PARTID__/$PARTID/"       \
               | sed "s/__PTMIN__/$PTMIN/"          | sed "s/__PTMAX__/$PTMAX/"         \
               | sed "s/__ETAMIN__/$ETAMIN/"        | sed "s/__ETAMAX__/$ETAMAX/"       \
               | sed "s/__PHIMIN__/$PHIMIN/"        | sed "s/__PHIMAX__/$PHIMAX/"       \
                   > $CFGTMP
    fi

    if test -z "$NOCMSRUN"; then 
        cmsRun $CFGTMP $2 $3 $4 $5 $6 $7 $8 $9
        rm -f $CFGTMP
    fi
else
    echo "$0: Can not find config file: $1"
fi
